### ISSUE TITLE
error TS2304: Cannot find name 'Map'.

### ISSUE THREAD

**Issue by ctaggart** [ajafff/tsutils#13]
C:\Users\camer\ts\TsAst [base-class ≡ +0 ~4 -0 !]> tsc
node_modules/tsutils/util/usage.d.ts(30,74): error TS2304: Cannot find name 'Map'.

c:\Users\camer\ts\TsAst\node_modules\tsutils\util\usage.d.ts

``` ts
export declare function collectVariableUsage(sourceFile: ts.SourceFile): Map<ts.Identifier, VariableInfo>;
```

``` json
  "dependencies": {
    "@types/node": "^8.0.51",
    "tsutils": "^2.12.2",
    "typescript": "^2.6.1"
  },
```

![image](https://user-images.githubusercontent.com/80104/32972001-aedda70c-cbce-11e7-9664-1cf32be2bc9c.png)

**Comment by ajafff** [comment]
since TypeScript also uses `Map` internally, you need to run in an environment that supports at least ES6.
just add `{"compilerOptions": {"lib": ["ES6"]}` to your tsconfig.json to tell TypeScript to provide typings for ES6 features

**Comment by ctaggart** [comment]
Thank you.

**Comment by tlubitz** [comment]
Thanks, man, that helped!
