### ISSUE TITLE
How to I get the moduleName for each SourceFile?

### ISSUE THREAD

**Issue by ctaggart** [ajafff/tsutils#14]
Is there a way to get the `moduleName`s for a SourceFile? They are all showing up as `uknown` when I do this?
http://www.typescriptlang.org/docs/handbook/module-resolution.html

``` ts
import * as ts from "typescript";
import * as fs from "fs";
// import {isTypeReference, isClassDeclaration} from "tsutils";

const tsPath = "node_modules/@types/mocha/index.d.ts"
const options: ts.CompilerOptions = { target: ts.ScriptTarget.ES2015 }
const host = ts.createCompilerHost(options, true);
const program = ts.createProgram([tsPath], options, host)
const checker = program.getTypeChecker()

for (const sf of program.getSourceFiles()){
    console.log(sf.fileName + ": " + sf.moduleName)
}
```

```
C:\Users\camer\ts\TsAst [moduleName +1 ~0 -0 !]> node .\modulename.js
C:/Users/camer/ts/TsAst/node_modules/typescript/lib/lib.es6.d.ts: undefined
node_modules/@types/mocha/index.d.ts: undefined
C:/Users/camer/ts/TsAst/node_modules/@types/node/inspector.d.ts: undefined
C:/Users/camer/ts/TsAst/node_modules/@types/node/index.d.ts: undefined
```

**Comment by ajafff** [comment]
`SourceFile.moduleName` is only preset for AMD modules.

Can you describe which information you are trying to get from this property?

**Comment by ctaggart** [comment]
I want to generate import statement for each of the exports.  To correctly generate imports, I need to know the module name and the name of the item being exported. Here, I'm trying to get `mocha` as the `moduleName`.

**Comment by ctaggart** [comment]
I can string split on `/`, I just thought there may be a way to get it from the API.

**Comment by ajafff** [comment]
I'm afraid there is no ready-to-use solution. You need to use `fileName` and try to find an algorithm that works for all cases.

I'd suggest:

* find the last `node_modules` in the name
* if the directory after `node_modules` starts with an \@, it's a scoped package -> use the next directory name, too
* if the scope is `@types`, remove it
  * according to https://github.com/Microsoft/TypeScript/issues/14819 you need to convert the second directory name as well if it is a scoped package
  * `@types/slack__client` -> `@slack/client`
* you probably need some special handling for submodule imports
  * for example `@angular/common/http` is not exported from `@angular/common`
  * you probably need to read the package.json's `main` property to get this right

**Comment by ctaggart** [comment]
Thanks, I'll give that a shot.
