### ISSUE TITLE
Help maintaining this project?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ajafff/tsutils#145]
tsutils is a wonderful project used in a lot of other open source libraries, including typescript-eslint. But there hasn't been any maintenance activity -commits, issue triage, PR review, etc.- in a few months that I can see.

Would you be interested in having someone help out with the repo, @ajafff? I volunteer! 🙂 

ref: https://github.com/typescript-eslint/typescript-eslint/issues/5552

**Comment by JoshuaKGoldberg** [comment]
Ping @ajafff - I'm thinking of forking the project into some new name to address the issues. Please let me know if there's a better path forward! I'd prefer not to fork if at all possible.

**Comment by bradzacher** [comment]
For context - a lot of the ecosystem relies on this package (for example the type-aware linting ecosystem supported by @typescript-eslint).

Our tooling needs to keep pace with TS itself (or else people can't lint their code) so we're in a unique position to keep the package updated with new TS releases.

We'd love to avoid fragmenting the ecosystem by forking and instead take ownership of the npm package name, @ajafff.

If you'd like to remain on as a maintainer - we're happy to work something out!

**Comment by JoshuaKGoldberg** [comment]
Just following up, https://github.com/JoshuaKGoldberg/ts-api-utils is generally used as a replacement now. Cheers!
