### ISSUE TITLE
util request - line count

### ISSUE THREAD

**Issue by aervin** [ajafff/tsutils#56]
Some [recent](https://github.com/palantir/tslint/issues/3849) (and not-so-recent) rule requests hinge on the ability to accurately detect the number of lines spanned by a given piece of code. Something like this would be very helpful:
```ts
const lineCount: number = getNewlineCount(node);
``` 
Of course, some variations may be needed, specifically the option to ignore lines w/ comments only.

**Comment by ajafff** [comment]
This needs a very good proposal to be actionable. There are too many things that need to be considered:

* empty lines
* comment only lines
* nested classes and and functions
  * what about inline function expressions
* multiline strings and template strings
* basically everything in https://github.com/palantir/tslint/pull/2882

I would prefer not to add such a functionality to this library as every user has it's own requirements how lines should be counted.
