### ISSUE TITLE
Typescript 3 compatibility

### ISSUE THREAD

**Issue by zerkms** [ajafff/tsutils#75]
Typescript v3 was released today

This issue is to track the `tsutils` project compatibility with it

**Comment by ajafff** [comment]
It's compatible. It's already used in CI for a few days.

**Comment by zerkms** [comment]
```
  "peerDependencies": {
    "typescript": ">=2.8.0 || >= 3.1.0-dev"
  }
```

`peerDependencies` does not allow it though

```
npm WARN tsutils@2.8.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >= 2.4.0-dev || >= 2.5.0-dev || >= 2.6.0-dev but none is installed. You must install peer dependencies yourself.
```

**Comment by ajafff** [comment]
Reopening until this is resolved. Please continue discussion in https://github.com/fimbullinter/wotan/issues/355 as this is the same issue

**Comment by zerkms** [comment]
Right, I bumped `typescript` dependency to `^3.0.0` but seems like transitive dependencies did not allow it to install. Sorry!
