### ISSUE TITLE
Get the text of a comment??

### ISSUE THREAD

**Issue by kferrone** [ajafff/tsutils#80]
Would be nice to see a really good example of getting comments from TS using your package. I found out about `tsutils` from [this post](https://github.com/Microsoft/TypeScript/issues/21049) but could not quite get it to work like I want. 

I also tried an official example from Typescript but ran into problems as well. 
[Typescript Compiler Example for Type Checker](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker)
[Issue I posted about the problem](https://github.com/Microsoft/TypeScript/issues/26911)

Basically I can only ever get an object with the position of comments but not the text itself or anything else out of it. 

Here is my code below: 

```
import * as utils from 'tsutils';
import * as ts from 'typescript';
import {SourceFile} from 'typescript';

function generateDocumentation(
  fileNames: string[],
  options: ts.CompilerOptions
): void {

    // Build a program using the set of root file names in fileNames
    let program = ts.createProgram(fileNames, options);

    // Visit every sourceFile in the program
    for (const sourceFile of program.getSourceFiles()) {
        if (!sourceFile.isDeclarationFile) {
            
            // Walk the tree to search for classes
            //ts.forEachChild(sourceFile, visit);
            visit(sourceFile,sourceFile);
        }
    }

    return;

    /** visit nodes finding exported classes */
    function visit(node: ts.Node, src: SourceFile) {

        utils.forEachComment(node, (fullText: string, comment: ts.CommentRange) => {
            console.log('--- The comment object looks like below ---');
            console.dir(comment);
            //this line definitely does not get the text of the comment, but what does????
            var commentStr: ts.CommentRange = utils.getCommentAtPosition(src,comment.pos);
            console.log('The comment text is ', commentStr);
            console.log('--- --- --- --- ---');
        });

    }

}

generateDocumentation(
    ['src/controllers/testController.ts'], 
    {
        target: ts.ScriptTarget.Latest,
        module: ts.ModuleKind.CommonJS
    }
);
```

Any chance of some more docs on how to use this package? A good example of getting and displaying comments would be sooooo useful.

**Comment by ajafff** [comment]
If you already have a `ts.CommentRange`, you no longer need `getCommentAtPosition`.
Instead you simply use the offset it contains:

```ts
const commentStr = src.text.substring(comment.pos, comment.end): // contains the leading '//' or '/*' and '*/'
```

Also note that if you are looking for documentation comments, you should prefer `utils.getJsDoc` which returns the readily parsed JSDoc comments of a node.

**Comment by kferrone** [comment]
OK so I've been trying to get the `utils.getJsDoc` to work but to no avail as it always returns an empty array for me??? I tried `console.log('the docs are ', utils.getJsDoc(node));` in numerous places in the code above and no matter what I always end up with an empty array???

Example please???

**Comment by ajafff** [comment]
First of all, TypeScript only attaches JSDoc comments to specific declarations. You can test if a certain node could have JSDoc attached by using `utils.canHaveJsDoc(node)`. If that function returns `false`, `utils.getJsDoc` will always return an empty array for that node.

There's nothing surprising about using these functions:

```ts
import * as ts from 'typescript';
import * as utils from 'tsutils';

declare const sourceFile: ts.SourceFile;

function visit(node: ts.Node): void {
  if (utils.canHaveJsDoc(node))
    console.log(utils.getJsDoc(node, sourceFile);
  ts.forEachChild(node, visit); // note that forEachChild only visits every __immediate__ child so you need to do the recursion yourself
}
```
