### ISSUE TITLE
Feature request: New util to find all imports

### ISSUE THREAD

**Issue by pe8ter** [ajafff/tsutils#81]
_tsutils_ has a function `findImports()` that finds imports where the argument to the import is a string literal:

```typescript
const foo = require('foo');
```

but does not find imports where the argument is dynamically constructed:

```typescript
const myPath = resolvePathSomehow();
const bar = require(myPath);
```

It would be handy to have a function that finds this second case for a library like _tslint_ which has a linting rule `no-require-imports` which should find all occurrences of the `require()` function, regardless of its argument, but doesn't since it uses the current implementation of `findImports()`. See [this item](https://github.com/palantir/tslint/issues/4177).

**Comment by ajafff** [comment]
`v3.2.0` contains a new function `findImportLikeNodes` that works similar to `findImports`. It doesn't filter and returns the parent nodes (e.g. CallExpression for `require(myPath)`) instead.
