### ISSUE TITLE
unable to install tsutils 3.2.0 using npm (typescript version 3.1.3)

### ISSUE THREAD

**Issue by shahid-pk** [ajafff/tsutils#82]
I am getting this error while i try to install tsutill.

> npm WARN tsutils@3.2.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev but none is installed. You must install peer dependencies yourself.

tsc --version 

> Version 3.1.3

**Comment by ajafff** [comment]
and what is `node_modules/.bin/tsc --version`?

**Comment by shahid-pk** [comment]
`it is Version 2.7.2`

I was trying to install tsutils using the following command 

> npm install -g tsutils

as i wanted to install this package globally. and eventually tslint globally, tslint is faling because of tsutils. 
😃 
sorry if this is very noob question i am new npm/node comping from nuget/c#

**Comment by ajafff** [comment]
Installing them together in one command you work: `npm install -g typescript tslint`
IIRC that's what TSLint's docs suggest doing.

**Comment by shahid-pk** [comment]
Thanks my bad. Installed with no issues
