### ISSUE TITLE
getLineRanges reports contentLength of 1 for a file's first line if it's blank

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ajafff/tsutils#94]
See discussion in https://github.com/palantir/tslint/issues/4518. If a file contains these lines:

```ts

let 1 = 2;

let b = 2;
```

...then the reported `contentLength`s are:

* 1
* 10
* 0
* 10

**Comment by ajafff** [comment]
@JoshuaKGoldberg I cannot reproduce this. I created #95 to add some tests for this.

I guess the line is not really empty but contains a BOM. I don't know if this function is the right place to handle this.
