### ISSUE TITLE
IsNullLiteral and IsBooleanLiteral are missing

### ISSUE THREAD

**Issue by noamyogev84** [ajafff/tsutils#96]
Add Two functions to detect null, true, false literals. 🍺

**Comment by noamyogev84** [comment]
I'll be happy to address this. 👨‍⚕️

**Comment by ajafff** [comment]
What's the use case for these functions?
All of the existing type guards can be used to narrow `ts.Node` to a more specific type, e.g. `ts.Block`. The keywords above don't have specific types, so it would be `function isNullKeyword(node: ts.Node) node is ts.Node` which IMO serves no real purpose.
Is there a reason for not using `node.kind === ts.SyntaxKind.NullKeyword` directly in your code?

**Comment by noamyogev84** [comment]
I can think of a few benefits: 
1. Uniformity and readability (I don't think that narrowing the type should be the only reason to use `utils` in my code), and for sure I don't like to use 2 different approaches to "ask the same question".
2. `IsBooleanLiteral` should actually implement 2 checks against `syntaxtKind`, so why not encapsulate this?
3. In the scenario where a certain function receives a `ts.Node` and runs a set of validations based on its type, it'll be wise to narrow the type (e.g. narrow to `ts.NullLiteral` to prevent access to `text` property)

🍻

**Comment by ajafff** [comment]
I think you are mistaken on your 3rd benefit. You cannot access the `text` property on `ts.Node` unless you narrow to a more specific type that has this property.

I'm fine with adding such utility functions. Note that their name should match the corresponding `ts.SyntaxKind`, i.e. `isNullKeyword` for `ts.SyntaxKind.NullKeyword`.
The only exception would be `isBooleanLiteral` which checks for both `TrueKeyword` and `FalseKeyword` to disambiguate from `ts.SyntaxKind.BooleanKeyword`.
